//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATH_kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public int ID_Faktura { get; set; }
        public int ID_RodzajKosztow { get; set; }
        public decimal Koszt { get; set; }
        public string NumerDokumentu { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public System.DateTime DataOtrzymania { get; set; }
        public System.DateTime TerminZaplaty { get; set; }
        public Nullable<System.DateTime> DataZaplaty { get; set; }
    
        public virtual RodzajKosztow RodzajKosztow { get; set; }
    }
}
