//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATH_kino
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATH_kinoEntities : DbContext
    {
        public ATH_kinoEntities()
            : base("name=ATH_kinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktor> Aktor { get; set; }
        public virtual DbSet<Faktura> Faktura { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Gatunek> Gatunek { get; set; }
        public virtual DbSet<GatunekSzczegoly> GatunekSzczegoly { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Rezerwacja> Rezerwacja { get; set; }
        public virtual DbSet<Rezyser> Rezyser { get; set; }
        public virtual DbSet<RodzajKosztow> RodzajKosztow { get; set; }
        public virtual DbSet<Rola> Rola { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Scenarzysta> Scenarzysta { get; set; }
        public virtual DbSet<Seans> Seans { get; set; }
    }
}
