//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATH_kino
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacja
    {
        public int ID_Rezerwacja { get; set; }
        public int ID_Klient { get; set; }
        public int ID_Seans { get; set; }
        public int Miejsce { get; set; }
        public System.DateTime DataRezerwacji { get; set; }
        public decimal CenaBiletu { get; set; }
        public Nullable<double> ZnizkaProcent { get; set; }
        public string ZnizkaOpis { get; set; }
        public string ZnizkaNrDokumentu { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Seans Seans { get; set; }
    }
}
